LIBNAME ALURA "/home/u62784676/MyFolders/AluraPlay";

/* TABELA DE FREQUÊNCIA */
/* NLEVELS - FREQUÊNCIA DAS CATEGÓRIAS DA VARIÁVEL */
PROC FREQ
	DATA = ALURA.CADASTRO_PRODUTO NLEVELS;
	TABLE GENERO PLATAFORMA NOME;
RUN;

* MANIPULANDO BASE DE DADOS ;

/* CRIANDO UMA BASE TEMPORARIA COM "DATA" A PARTIR DE OUTRA BASE */
DATA TESTE;
SET ALURA.CADASTRO_PRODUTO;
IF DATA > 201606 
	THEN LANCAMENTO = 1;
	ELSE LANCAMENTO = 0;
RUN;

PROC PRINT
	DATA = TESTE NOOBS;
RUN;

/* LISTANDO A FREQUENCIA DE LANÇAMENTOS */
PROC FREQ 
	DATA = TESTE;
	TABLE LANCAMENTO;
RUN;

/* FREQUENCIA CRUZADA UTULIZANDO O * */
PROC FREQ
	DATA = TESTE;
	TABLE GENERO*LANCAMENTO;
RUN;

DATA ANTIGO;
SET ALURA.CADASTRO_PRODUTO;
IF DATA < 201401
	THEN ANTIGO = 1;
	ELSE ANTIGO = 0;
RUN;

PROC FREQ
	DATA = ANTIGO;
	TABLE ANTIGO;
RUN;


PROC FREQ
	DATA = TESTE NLEVELS;
	TABLE GENERO*LANCAMENTO;
RUN;

/* COSTUMIZANDO AS SAIDAS DE VALORES */
PROC FREQ
	DATA = TESTE;
	TABLE GENERO*LANCAMENTO
	/NOCOL NOROW NOFREQ;
RUN;


PROC FREQ
	DATA = ALURA.CADASTRO_PRODUTO NLEVELS;
	TABLE NOME;
	TABLE NOME*GENERO
	/LIST;
RUN;


/* CRIANDO UMA BASE PERMANENTE */
DATA ALURA.CADASTRO_PRODUTO_V2;
SET TESTE;
RENAME LANCAMENTO = FLAG_LANCAMENTO;
LABEL GENERO = "GÊNERO" 
	LANCAMENTO = "MARCA 1 PARA JOGOS QUE SÃO LANÇAMENTO E 0 CASO CONTRÁRIO";
RUN;

PROC CONTENTS
	DATA = ALURA.CADASTRO_PRODUTO_V2;
RUN;
